version: 2

jobs:
    build:
        docker:
            - image: circleci/node:latest

        branches:
            only:
                - developing
            ignore:
                - master
                - /dev-.*/     

        shell: /bin/bash           


        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"


        steps:
            # https://github.com/spf13/hugo/releases
            - run:
                name: Download Hugo
                command: wget -O hugo.deb https://github.com/spf13/hugo/releases/download/v0.27.1/hugo_0.27.1_Linux-64bit.deb
            - run:
                name: Install Hugo
                command: sudo dpkg -i hugo.deb
            # https://github.com/kangax/html-minifier    
            - run:
                name: Install HTML-Minifier
                command: sudo npm install -g html-minifier
            # https://github.com/svg/svgo
            - run:
                name: Install SVGO
                command: sudo npm install -g git+https://github.com/svg/svgo.git
            # https://github.com/fizker/minifier
            - run:
                name: Install Minifier
                command: sudo npm install -g git+https://github.com/fizker/minifier.git
            - checkout
            - run:
                name: Git Clean
                command: git clean -xdf
            - run:
                name: Git Remove Unused Branches
                command: git fetch -p
            - run:
                name: Git Prune
                command: git gc --prune=now
            - run:
                name: Build Hugo Website
                command: hugo --ignoreCache --cleanDestinationDir
            - run:
                name: Minify SVGs
                command: svgo --config=data/svgo.config public/images/
            - run:
                name: Minify HTML
                command: find public -type f -name "*.htm*" -exec data/minify.sh \{\} \;
            - run:
                name: Minify CSS
                command: find public -type f -name "*.css" -exec data/minify.sh \{\} \;
            - run:
                name: Minify JS
                command: find public -type f -name "*.js" -exec data/minifyjs.sh \{\} \;
            - store_artifacts:
                path: ~/public  

#- mv -f public /tmp
#deployment:
#    production:
#        branch: developing
#        commands:
#            - git push origin :master || true
#            - git brach -D master || true       
#            - git checkout --orphan master
#            - rm -Rf *
#            - mv -f /tmp/public/* .
#            - echo -e 'general:\n    branches:\n        ignore:\n            - master\n' > circle.yml
#            - echo -e '*.*\n!.gitignore\n!circle.yml\n!*.html\n!*.xml\n!*.css\n!*.js\n!*.json\n!*.bib\n!*.zip\n!*.png\n!*.gif\n!*.pdf\n!*.svg\n!*.txt\n' > .gitignore
#            - echo -e '# LightJason\n\nCurrent website of the [LightJason](http://lightjason.org) project' > readme.md
#            - git add --all .
#            - export GIT_COMMIT_MESSAGE="$(git show -s --pretty=format:%s $CIRCLE_SHA1)" && git commit -m "webpage update [$GIT_COMMIT_MESSAGE]"
#            - git push origin master
